### ISSUE TITLE
Install with errors, service fails to load

### ISSUE THREAD

**Issue by hhackbarth** [geekworm-com/ups3#2]
I determined a couple of problems. It was tested with Raspbian Buster (27th May 2020) on RPi 4B:

When executing the install script, it reports:
dpkg-query: no packages found matching scons

After going through the menu items of the install script and enabling the service, it fails to start.
This is, what systemctl reports (sorry for the truncated lines):
pi@raspberrypi:~/ups3 $ sudo systemctl status smartups.service
● smartups.service - ugeek smart ups v3
   Loaded: loaded (/etc/systemd/system/smartups.service; enabled; vendor
   Active: failed (Result: exit-code) since Thu 2020-07-02 22:28:04 CEST
  Process: 375 ExecStart=/usr/bin/sudo /usr/bin/python3 /usr/local/bin/s
 Main PID: 375 (code=exited, status=1/FAILURE)

Jul 02 22:28:04 raspberrypi systemd[1]: smartups.service: Service Restar
Jul 02 22:28:04 raspberrypi systemd[1]: smartups.service: Scheduled rest
Jul 02 22:28:04 raspberrypi systemd[1]: Stopped ugeek smart ups v3.
Jul 02 22:28:04 raspberrypi systemd[1]: smartups.service: Start request 
Jul 02 22:28:04 raspberrypi systemd[1]: smartups.service: Failed with re
Jul 02 22:28:04 raspberrypi systemd[1]: Failed to start ugeek smart ups 

When starting the smartups.py manually, this happens:
pi@raspberrypi:~/ups3 $ /usr/bin/sudo /usr/bin/python3 /usr/local/bin/smartups.py
Traceback (most recent call last):
  File "/usr/local/bin/smartups.py", line 12, in <module>
    from neopixel import *
  File "/usr/local/bin/neopixel.py", line 5, in <module>
    import _rpi_ws281x as ws
ModuleNotFoundError: No module named '_rpi_ws281x'

Hoping you can fix it soon.

**Comment by Nornode** [comment]
Yeah, seems like the install script don't install dependencies (python packages).
Did you ever solve this?

A much better way would be to solve and install the dependencies when actually executing the install script...

**Comment by crazynuxer** [comment]
try install python-pip or if you using python3 install python3-pip then modify the install script to use pip3, or set alias in bash shell
like `alias pip="pip3"`
