### ISSUE TITLE
The smartups.py service floods the smartups.log file

### ISSUE THREAD

**Issue by JardaG** [geekworm-com/ups3#4]
It logs almost every second (pls. see below) and the log file grows unnecessarily by about 6 MB in 24 hours and thus unnecessarily increases the memory card wear in RPi.

I suggest logging only when changing any of the parameters and at least once every 1 hour, if at all.

Sample from `/var/log/smartups.log` file:
```
2020-12-31 08:00:58,243  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:00:59,460  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:00,677  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:01,899  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:03,122  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:04,345  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:05,562  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:06,783  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:07,996  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:09,219  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:10,436  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:11,653  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:12,877  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:14,094  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:15,310  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:16,523  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:17,746  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:18,968  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:20,192  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:21,415  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:22,627  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:23,848  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:25,058  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:26,275  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:27,498  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
2020-12-31 08:01:28,714  smartups.py : INFO   Input:Connected , ChargeStatus: Charging done , SOC:91.171875%
```

**Comment by fabianmendes** [comment]
I got this problem.
```
pi@basiliscus:~ $ cd ups3
pi@basiliscus:~/ups3 $ chmod +x *.sh *.py
pi@basiliscus:~/ups3 $ sudo ./install.sh
Install Smart UPS Service.
dpkg-query: no se ha encontrado ningún paquete que corresponda con scons.
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/commands/search.py", line 48, in run
    pypi_hits = self.search(query, options)
  File "/usr/lib/python2.7/dist-packages/pip/_internal/commands/search.py", line 65, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/dist-packages/pip/_internal/download.py", line 791, in request
    return self.parse_response(response.raw)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault -32500: "RuntimeError: PyPI's XMLRPC API has been temporarily disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.">
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: rpi-ws281x in /usr/local/lib/python2.7/dist-packages (4.2.5)
rpi-ws281x install complete!
Service has been enabled.
Start service now.
Warning: The unit file, source configuration file or drop-ins of smartups.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Service successfully installed.
Service already stopped.
GPIO:12 Brightness:153 Shutdown power:5
Start service now.
Warning: The unit file, source configuration file or drop-ins of smartups.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for smartups.service failed because the control process exited with error code.
See "systemctl status smartups.service" and "journalctl -xe" for details.
pi@basiliscus:~/ups3 $ 

```
